FROM debian:trixie

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
    gettext git libncurses-dev libssl-dev python3-setuptools \
    rsync unzip zlib1g-dev file wget python3 \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash builduser
USER builduser
WORKDIR /home/builduser/openwrt
