name: Build RV2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install build prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y device-tree-compiler

    - name: Build Orange Pi RV2
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp orangepi_rv2_defconfig .config
        make defconfig
        make -j$(nproc) download
        make -j$(($(nproc)+1))
